### ISSUE TITLE
Could you please update this gem or update the gemspec?

### ISSUE THREAD

**Issue by kojix2** [nanki/ffi-portaudio#5]
I would like to use ffi-portaudio, but the changes in #4 have not been applied, so I need to patch it by myself even if I install the gem. If you install from source code, the version of the dependent library of the gem is outdated, so you need to rewrite the version of the dependent library. For example, using bundler 1.0 is a difficult thing to do in this day and age.
　Can I use gemspec to release a new gem or update the version of the dependent library?

Translated with www.DeepL.com/Translator (free version)

**Comment by nanki** [comment]
pushed!

https://rubygems.org/gems/ffi-portaudio/versions/0.1.3

**Comment by kojix2** [comment]
Thanks!

https://user-images.githubusercontent.com/5798442/137591571-40116152-bfa6-4645-937d-a91438e018e5.mp4

* ffi-portaudio
* [numo-fftw](https://github.com/ruby-numo/numo-fftw)
* [GR.rb](https://github.com/red-data-tools/GR.rb)

**Comment by kojix2** [comment]
I added the official LibUI sample using ffi-portaudio. Please take a look if you like.
https://github.com/kojix2/LibUI/blob/main/examples/spectrum.rb
